// 60 preguntas de la evaluación final del bloque 3.
// Importado desde Clase.jsx. Los IDs se usan como claves de useStoredValue.

export const TEST_DIVERSIFICACION = [
  {
    id: "test-div-1",
    pregunta: "Tienes 10 acciones tecnológicas estadounidenses. ¿Estás diversificado?",
    opciones: [
      "Sí, son 10 acciones distintas.",
      "Sí, son grandes y líquidas.",
      "No, todas comparten el mismo factor de riesgo.",
      "Depende del importe invertido.",
    ],
    correcta: 2,
    explicacion: "La diversificación se mide en fuentes de riesgo independientes, no en número de tickers. 10 tech-USA caen juntas si cambia la narrativa o suben los tipos.",
  },
  {
    id: "test-div-2",
    pregunta: "Una correlación ρ = −1 entre dos activos significa:",
    opciones: ["Son independientes.", "Son idénticos.", "Se mueven en direcciones exactamente opuestas siempre.", "Están en el mismo sector."],
    correcta: 2,
    explicacion: "ρ = −1 es correlación perfectamente negativa. En la práctica casi no existe entre acciones cotizadas.",
  },
  {
    id: "test-div-3",
    pregunta: "Una cartera con SPY + GLD + TLT está diversificada por:",
    opciones: ["Sectores únicamente.", "Clases de activo (acciones, oro, bonos).", "Geografía únicamente.", "Tamaño de empresa."],
    correcta: 1,
    explicacion: "SPY (acciones), GLD (oro), TLT (bonos largos) son tres clases de activo distintas. Es el nivel de diversificación más profundo.",
  },
  {
    id: "test-div-4",
    pregunta: "En periodos de estrés del mercado, la correlación entre activos tiende a:",
    opciones: ["Mantenerse estable.", "Bajar (los activos se separan).", "Subir (los activos caen juntos).", "Volverse negativa."],
    correcta: 2,
    explicacion: "En crisis, las correlaciones suben hacia 1: 'todo cae junto'. Por eso hay que medir ρ en períodos largos que incluyan crisis.",
  },
  {
    id: "test-div-5",
    pregunta: "El factor que MÁS comparten una acción tech, un REIT y una utility es:",
    opciones: ["Tamaño (small cap).", "Sensibilidad a tipos de interés.", "Sensibilidad al precio del petróleo.", "Exposición geográfica."],
    correcta: 1,
    explicacion: "Las tres son sensibles a tipos: tech porque sus beneficios futuros valen menos; REITs porque pagan dividendos altos; utilities porque tienen mucha deuda. En 2022 cayeron juntas.",
  },
  {
    id: "test-div-6",
    pregunta: "Un Diversification Ratio de 1,05 significa:",
    opciones: ["Excelente diversificación.", "La cartera reduce el riesgo en un 5%.", "Casi no hay reducción de riesgo (correlación interna alta).", "Imposible matemáticamente."],
    correcta: 2,
    explicacion: "DR = σ_media_ponderada / σ_cartera. Cerca de 1 = la diversificación apenas reduce riesgo. >1,4 buena. >1,6 excelente.",
  },
  {
    id: "test-div-7",
    pregunta: "Un inversor europeo con S&P 500 sin cubrir divisa, si el dólar SE FORTALECE frente al euro:",
    opciones: ["Pierde rentabilidad por divisa.", "Gana rentabilidad por divisa.", "No le afecta porque la posición es en USD.", "Solo le afecta si vende."],
    correcta: 1,
    explicacion: "Cuando el dólar se fortalece, el inversor en euros gana extra: cada dólar repatriado vale más en euros.",
  },
  {
    id: "test-div-8",
    pregunta: "Iberdrola y Endesa probablemente tienen una correlación cercana a:",
    opciones: ["−0,5", "0,0", "+0,3", "+0,85"],
    correcta: 3,
    explicacion: "Mismo sector, misma región, mismas variables (precio gas, regulación). ρ típica entre 0,80 y 0,90. Combinarlas NO es diversificar.",
  },
  {
    id: "test-div-9",
    pregunta: "El par menos correlacionado en una cartera es valioso porque:",
    opciones: ["Es el que más rentabilidad aporta.", "Es el que más reduce el riesgo total.", "Es el más barato.", "Es el más volátil."],
    correcta: 1,
    explicacion: "El par con menor ρ es la 'joya diversificadora': son los dos activos que más se cancelan mutuamente y reducen la volatilidad total.",
  },
  {
    id: "test-div-10",
    pregunta: "Tienes una cartera con corr media 0,82. Decisión más sensata:",
    opciones: ["Mantener todo, ya que rinde bien.", "Añadir más activos del mismo tipo.", "Sustituir 1-2 activos por otros de baja correlación con los actuales.", "Cerrar toda la cartera."],
    correcta: 2,
    explicacion: "Una correlación media de 0,82 es 'diversificación falsa'. La acción correcta es identificar el par más correlacionado y sustituir uno por un activo de OTRA clase o factor.",
  },
];

export const ABIERTAS_DIVERSIFICACION = [
  { id: "abierta-div-1", pregunta: "Explica con tus palabras qué es la correlación, sin usar fórmulas matemáticas, en 3-4 líneas." },
  { id: "abierta-div-2", pregunta: "Define 'diversificación falsa por factor' con un ejemplo propio (no uses los ejemplos vistos en clase)." },
  { id: "abierta-div-3", pregunta: "¿Por qué la correlación cambia en periodos de crisis? Explica el mecanismo en 4-5 líneas." },
  { id: "abierta-div-4", pregunta: "Un compañero te dice: 'tengo 20 acciones distintas, estoy súper diversificado'. ¿Qué le contestas? Justifica." },
  { id: "abierta-div-5", pregunta: "Tu cartera tiene correlación media 0,82 y diversification ratio 1,05. Plan de acción concreto en 3 pasos." },
  { id: "abierta-div-6", pregunta: "Explica el efecto divisa para un inversor en euros que invierte en S&P 500. Da un ejemplo numérico inventado." },
  { id: "abierta-div-7", pregunta: "Cartera A: SPY + QQQ + IWM (3 ETFs USA). Cartera B: SPY + EEM + EWJ (USA + emergentes + Japón). ¿Cuál diversifica más y por qué?" },
  { id: "abierta-div-8", pregunta: "Define el 'diversification ratio' con tus palabras y di qué umbrales consideras buenos." },
  { id: "abierta-div-9", pregunta: "¿Por qué la diversificación geográfica no siempre funciona? Da un caso histórico real." },
  { id: "abierta-div-10", pregunta: "Si solo pudieras añadir UN activo a tu cartera actual para diversificar más, ¿qué tipo de activo elegirías y por qué? Justifica con datos de tu cartera real." },
];

export const TEST_GESTIONMON = [
  {
    id: "test-gm-1",
    pregunta: "Tienes 20.000€ y arriesgas 1% por operación. Compras a 100€ con stop a 95€. ¿Cuántas acciones?",
    opciones: ["20", "40", "200", "400"],
    correcta: 1,
    explicacion: "Riesgo = 20.000 × 1% = 200€. Distancia stop = 100−95 = 5€. Acciones = 200/5 = 40.",
  },
  {
    id: "test-gm-2",
    pregunta: "Tu cuenta cae un 40% desde el máximo. ¿Cuánto necesitas ganar para recuperarte?",
    opciones: ["+40%", "+50%", "+66,7%", "+100%"],
    correcta: 2,
    explicacion: "% recuperación = 40/(1−0,40) = 40/0,60 = 66,67%. La asimetría se acelera con caídas profundas.",
  },
  {
    id: "test-gm-3",
    pregunta: "Sistema A: 70% aciertos, R/R 0,5. Sistema B: 40% aciertos, R/R 2. ¿Cuál tiene mayor esperanza por operación?",
    opciones: ["A", "B", "Empatan", "Faltan datos"],
    correcta: 1,
    explicacion: "A: 0,70×0,5 − 0,30×1 = 0,05. B: 0,40×2 − 0,60×1 = 0,20. B gana 4× más por operación.",
  },
  {
    id: "test-gm-4",
    pregunta: "El % de riesgo recomendado por operación es:",
    opciones: ["0,1%-0,3%", "0,5%-2%", "5%-10%", "10%-20%"],
    correcta: 1,
    explicacion: "Estándar profesional: 0,5% a 2% por operación. Permite encajar 50+ pérdidas seguidas sin arruinarse.",
  },
  {
    id: "test-gm-5",
    pregunta: "La martingala es matemáticamente atractiva pero falla en la práctica porque:",
    opciones: ["Los brokers la prohíben.", "Es ilegal en España.", "El tamaño exigido crece exponencialmente y supera el capital disponible en pocas pérdidas seguidas.", "Solo funciona en mercados alcistas."],
    correcta: 2,
    explicacion: "Tras 7 pérdidas seguidas, el tamaño exigido es 128× el inicial. Cualquier capital realista se agota antes.",
  },
  {
    id: "test-gm-6",
    pregunta: "Un sistema con 30% aciertos puede ser ganador si:",
    opciones: ["Es imposible.", "El R/R es mayor que 2,33.", "Acierta 5 veces seguidas.", "Solo si opera en mercados emergentes."],
    correcta: 1,
    explicacion: "E≥0 requiere R/R ≥ (1−win)/win = 0,70/0,30 = 2,33. Acertar poco con buen R/R puede ser muy rentable.",
  },
  {
    id: "test-gm-7",
    pregunta: "El stop loss debe colocarse:",
    opciones: ["Siempre al 5% del precio de entrada.", "Donde el precio invalida la tesis técnica (soporte/resistencia).", "Lo más cerca posible para perder poco.", "Lo más lejos posible para no saltar."],
    correcta: 1,
    explicacion: "Stop técnico: donde la tesis deja de tener sentido. Si está demasiado cerca salta por ruido; si está demasiado lejos, pierdes mucho.",
  },
  {
    id: "test-gm-8",
    pregunta: "Una racha de 6 pérdidas seguidas con win rate 50% ocurre con probabilidad:",
    opciones: ["0,001%", "1,5%", "10%", "50%"],
    correcta: 1,
    explicacion: "0,5^6 = 1,5625%. En 100 operaciones, esperas ver al menos 1 racha así. Por eso la martingala es ruinosa.",
  },
  {
    id: "test-gm-9",
    pregunta: "La antimartingala consiste en:",
    opciones: ["Reducir tamaño tras pérdidas y aumentar tras ganancias.", "Doblar tras pérdidas.", "Mantener tamaño fijo siempre.", "Solo abrir posiciones cuando se gane."],
    correcta: 0,
    explicacion: "Aumentar tras ganancias (capitalizar rachas buenas) y reducir tras pérdidas (proteger en rachas malas). Base de la gestión profesional.",
  },
  {
    id: "test-gm-10",
    pregunta: "A largo plazo, lo que más importa para la rentabilidad NO es:",
    opciones: ["El % de riesgo por operación.", "El ratio R/R.", "El % de aciertos absoluto.", "La esperanza matemática del sistema."],
    correcta: 2,
    explicacion: "El % de aciertos AISLADO no dice nada. Lo que importa es la esperanza (combinación de win rate, ganancia media y pérdida media).",
  },
];

export const ABIERTAS_GESTIONMON = [
  { id: "abierta-gm-1", pregunta: "Explica por qué un trader con 35% de aciertos puede ser ganador a largo plazo. Usa números." },
  { id: "abierta-gm-2", pregunta: "¿Por qué la gestión monetaria es más importante que el análisis técnico para la rentabilidad de largo plazo?" },
  { id: "abierta-gm-3", pregunta: "Define tu % de riesgo personal por operación y justifica el número con tu situación (capital, frecuencia, tolerancia)." },
  { id: "abierta-gm-4", pregunta: "Tienes una operación abierta que va +50%. ¿Qué haces? Define tu plan en 3 acciones posibles y elige justificando." },
  { id: "abierta-gm-5", pregunta: "Explica con un ejemplo numérico la asimetría drawdown/recuperación: parte de 10.000€ y aplica caídas del 20%, 40% y 60%." },
  { id: "abierta-gm-6", pregunta: "¿Por qué la martingala falla en la práctica aunque parezca matemáticamente sólida? Cita 3 problemas concretos." },
  { id: "abierta-gm-7", pregunta: "Diseña un sistema con esperanza matemática positiva mínima: define win rate, R/R, y verifica que E≥0." },
  { id: "abierta-gm-8", pregunta: "¿Cómo decides la posición del stop loss en una operación: técnico (soporte/resistencia) o porcentaje fijo? Justifica." },
  { id: "abierta-gm-9", pregunta: "Diferencia 'riesgo asumido' (lo que pones) de 'riesgo controlado' (lo que puedes perder máximo). Da un ejemplo de cada." },
  { id: "abierta-gm-10", pregunta: "Tienes 2 sistemas con misma esperanza matemática (E=+50€/op) pero distinto Max Drawdown (sistema A: −15%, sistema B: −35%). ¿Cuál usarías y por qué?" },
];

export const TEST_CARTERAS = [
  {
    id: "test-cart-1",
    pregunta: "La decisión que MÁS explica el resultado de una cartera a largo plazo es:",
    opciones: ["Acertar las acciones concretas.", "El asset allocation entre clases.", "El timing de entrada.", "El bróker elegido."],
    correcta: 1,
    explicacion: "Estudios académicos (Brinson 1986 y replicaciones) muestran que >80% de la varianza del rendimiento se explica por la asignación entre clases.",
  },
  {
    id: "test-cart-2",
    pregunta: "Tu cartera tiene β = 0,7. El S&P cae −20%. ¿Tu cartera aproximadamente?",
    opciones: ["Cae −7%", "Cae −14%", "Cae −20%", "Sube +6%"],
    correcta: 1,
    explicacion: "β × movimiento = 0,7 × −20% = −14%. Beta amortigua tanto subidas como caídas.",
  },
  {
    id: "test-cart-3",
    pregunta: "Tu cartera 60/40 ha pasado a 75/25 tras 3 años. ¿Qué deberías hacer?",
    opciones: ["Mantener.", "Rebalancear vendiendo RV y comprando RF.", "Aumentar más la RV.", "Esperar a que caiga sola."],
    correcta: 1,
    explicacion: "Una cartera 75/25 ya NO es la 60/40 que decidiste. Es agresiva, no moderada. Rebalancear respeta tu plan original.",
  },
  {
    id: "test-cart-4",
    pregunta: "Sortino vs Sharpe: la diferencia clave es:",
    opciones: ["Sortino se calcula mensualmente, Sharpe anualmente.", "Sortino solo cuenta la volatilidad a la baja (caídas).", "Sharpe es para fondos, Sortino para particulares.", "Son iguales."],
    correcta: 1,
    explicacion: "Sortino penaliza solo las caídas (downside deviation). Es más justo: la volatilidad al alza no es 'mala'.",
  },
  {
    id: "test-cart-5",
    pregunta: "El rebalanceo OBLIGA a:",
    opciones: ["Comprar lo que ha subido.", "Vender lo que ha bajado.", "Vender lo que ha subido y comprar lo que ha bajado.", "Mantener todo igual."],
    correcta: 2,
    explicacion: "Rebalancear es vender ganadores (tomar beneficios en máximos) y comprar perdedores (acumular en mínimos). Disciplina contracíclica.",
  },
  {
    id: "test-cart-6",
    pregunta: "Una cartera con SPY 33% + GLD 33% + NVDA 33% en CAPITAL, en RIESGO probablemente:",
    opciones: ["Está repartida igual (33% cada uno).", "NVDA domina porque es mucho más volátil.", "GLD domina porque es defensivo.", "SPY domina por su tamaño."],
    correcta: 1,
    explicacion: "NVDA con σ ≈ 45% domina el riesgo aunque pese 33% en capital. La volatilidad multiplica el peso.",
  },
  {
    id: "test-cart-7",
    pregunta: "El 'riesgo de cola' (tail risk) se refiere a:",
    opciones: ["Caídas habituales del 5%.", "Eventos raros pero severos (crisis, gaps, correlaciones a 1).", "Operaciones cortas.", "Riesgo de ETFs apalancados."],
    correcta: 1,
    explicacion: "Tail risk: eventos de baja probabilidad pero alto impacto. Las distribuciones reales tienen 'colas gordas'. Marzo 2020 fue un evento de cola.",
  },
  {
    id: "test-cart-8",
    pregunta: "Investment Policy Statement (IPS) recoge:",
    opciones: ["Solo el % objetivo de RV.", "Solo las restricciones legales.", "Objetivos, horizonte, restricciones, tolerancia y reglas de la cartera.", "El listado de acciones a comprar."],
    correcta: 2,
    explicacion: "El IPS es el 'manual de instrucciones' de tu cartera: qué buscas, qué no aceptas, qué reglas aplicas. Sin IPS, las decisiones son arbitrarias.",
  },
  {
    id: "test-cart-9",
    pregunta: "Tracking Error mide:",
    opciones: ["Rentabilidad de la cartera.", "Cuánto se desvía la cartera del benchmark.", "Costes de transacción.", "Riesgo absoluto."],
    correcta: 1,
    explicacion: "TE es la desviación estándar de la diferencia (cartera − benchmark). Mide el 'riesgo activo' al separarse del índice.",
  },
  {
    id: "test-cart-10",
    pregunta: "Una cartera con NVDA + PLD (REIT) + NEE (utility) está expuesta principalmente a:",
    opciones: ["Riesgo de divisa.", "Riesgo de liquidez.", "Subidas de tipos de interés (los 3 son sensibles a tipos).", "Riesgo geopolítico."],
    correcta: 2,
    explicacion: "Tres sectores distintos pero un mismo factor: sensibilidad a tipos. Tech (beneficios futuros), REIT (dividendos), utility (deuda). En 2022 cayeron las 3 juntas.",
  },
];

export const ABIERTAS_CARTERAS = [
  { id: "abierta-cart-1", pregunta: "Define tu perfil de riesgo (conservador/moderado/agresivo) con 4 criterios: capacidad financiera, horizonte temporal, tolerancia psicológica, conocimiento. Y construye una cartera coherente en %." },
  { id: "abierta-cart-2", pregunta: "Tu cartera ha pasado de 60/40 a 80/20 tras 4 años de bull market en RV. Plan concreto en 3 pasos." },
  { id: "abierta-cart-3", pregunta: "Define tu plan de actuación predefinido para 3 escenarios extremos: drawdown del 15%, volatilidad doble, una posición que pesa más del 25% del total." },
  { id: "abierta-cart-4", pregunta: "Explica con tus palabras la diferencia entre alfa y beta. Da un ejemplo concreto que las distinga." },
  { id: "abierta-cart-5", pregunta: "¿Por qué el rebalanceo es contraintuitivo y aún así funciona? Explica con un ejemplo de bull market y bear market." },
  { id: "abierta-cart-6", pregunta: "Diseña un cuadro de mando con 5 métricas para revisar tu cartera mensualmente. Justifica cada elección." },
  { id: "abierta-cart-7", pregunta: "De los 7 riesgos ocultos vistos (concentración, correlación, volatilidad, drawdown, liquidez, divisa, cola), ¿cuál crees que más afecta a TU cartera actual y por qué?" },
  { id: "abierta-cart-8", pregunta: "Compara los métodos 'pesos iguales' y 'pesos por volatilidad objetivo' para una cartera de 3 activos. Ventajas y desventajas de cada uno." },
  { id: "abierta-cart-9", pregunta: "Si los tipos de interés suben 2pp en los próximos 12 meses, ¿cómo cambiaría tu cartera actual? Identifica activos perdedores y ganadores." },
  { id: "abierta-cart-10", pregunta: "Redacta TU Investment Policy Statement personal en 5 puntos: objetivo, horizonte, perfil de riesgo, restricciones y reglas de revisión." },
];
